/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ggtranslate;

import com.google.cloud.translate.Detection;
import static com.mycompany.ggtranslate.JavaSoundRecorder.RECORD_TIME;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 *
 * @author VuDuc
 */
public class MainScreen extends javax.swing.JFrame {
    
    TranslateAPI translateAPI;
    ArrayList<Language> listLanguage;
    LanguageDAO db;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        translateAPI = new TranslateAPI();
        db = new LanguageDAO();
        listLanguage = db.getLanguageList();
        listLanguage.sort(new Comparator<Language>(){
            @Override
            public int compare(Language o1, Language o2) {
                return o1.getLanguage().compareToIgnoreCase(o2.getLanguage());
            }
        });
        listLanguage.add(0, new Language("Auto detect", "ad"));
        int i = 0;
        for(Language l : listLanguage){
            comboBoxInput.addItem(l.getLanguage());
            if(i != 0){
                comboBoxOutput.addItem(l.getLanguage());
            }
            else i = 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTranslate = new javax.swing.JButton();
        comboBoxInput = new javax.swing.JComboBox<>();
        comboBoxOutput = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        btnSpeechOutput = new javax.swing.JButton();
        btnSpeechInput = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clone GG Translate");

        btnTranslate.setText("Translate");
        btnTranslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranslateActionPerformed(evt);
            }
        });

        txtInput.setColumns(20);
        txtInput.setLineWrap(true);
        txtInput.setRows(5);
        txtInput.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtInput);

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setLineWrap(true);
        txtOutput.setRows(5);
        txtOutput.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtOutput);

        btnSpeechOutput.setText("Speech");

        btnSpeechInput.setText("Speech");
        btnSpeechInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeechInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxInput, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSpeechInput))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(btnSpeechOutput))
                            .addComponent(jScrollPane4)))
                    .addComponent(btnTranslate))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpeechOutput)
                    .addComponent(btnSpeechInput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnTranslate)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranslateActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        String sourceString;
        if(comboBoxInput.getSelectedIndex() == 0){
            List<String> input = new ArrayList<>();
            input.add(text);
            List<Detection> detect = translateAPI.getDetection(input);
            sourceString = detect.get(0).getLanguage();
            int t = getLanguageByAcronym(sourceString);
            if(t != -1){
                comboBoxInput.setSelectedIndex(t);
            }
        }
        else{
            Language source = listLanguage.get(comboBoxInput.getSelectedIndex());
            sourceString = source.getAcronym();
        }
        Language target = listLanguage.get(comboBoxOutput.getSelectedIndex() + 1);
        String out = translateAPI.translate(text, sourceString, target.getAcronym());
        txtOutput.setText(out);
    }//GEN-LAST:event_btnTranslateActionPerformed

    private void btnSpeechInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeechInputActionPerformed
        // TODO add your handling code here:
        if(btnSpeechInput.isSelected()){
            btnSpeechInput.setText("Stop");
            JavaSoundRecorder recorder = new JavaSoundRecorder();
            Thread stopper = new Thread(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(RECORD_TIME);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
                recorder.finish();
            }
        });
        
        stopper.start();
        
        // start recording
        recorder.start();
        }
    }//GEN-LAST:event_btnSpeechInputActionPerformed

    private int getLanguageByAcronym(String acronym){
        for(int i = 0; i<listLanguage.size(); i++){
            Language l = listLanguage.get(i);
            if(l.getAcronym().compareTo(acronym) == 0){
                return i;
            }
        }
        return -1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSpeechInput;
    private javax.swing.JButton btnSpeechOutput;
    private javax.swing.JButton btnTranslate;
    private javax.swing.JComboBox<String> comboBoxInput;
    private javax.swing.JComboBox<String> comboBoxOutput;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtInput;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
